services:
    db:
        image: postgres
        restart: always
        container_name: dfl-db
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: mysecretpassword
            POSTGRES_DB: local
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - app-network
    dfl:
        env_file: .env
        platform: linux/amd64
        build:
            context: .
            dockerfile: dockerfile
        image: dfl-image
        container_name: dfl
        restart: always
        depends_on:
            - db
        ports:
            - 3000:3000
        volumes:
            - ./content:/app/content
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    pgdata:
